### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np
N=5
mas1=np.arange( N-1, -1 , -1 )
print('Массив от ' + str(N-1) + ' до 0: ' +  str(mas1))

Массив от 4 до 0: [4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [2]:
mas2=np.diag(mas1, k=0)
print('Единичная матрица с элементами из предыдущего задандания по диагонали:')
print(mas2)
print('Сумма диагональных элементов: ' + str(sum(sum(mas2))))

Единичная матрица с элементами из предыдущего задандания по диагонали:
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
Сумма диагональных элементов: 10


### Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [3]:
import pandas as pd
ratings = pd.read_csv('ratings.csv')
list_of_best=(ratings.query('rating >= {}'.format(5)).filter(items = ['userId'])['userId'].unique())
### Сначала создадим список(pandas) фильмов  с наивысшими оценоками пользователей - list_of_best ###
list_of_film_ratings=list(list_of_best)
### Затем подсчитаем сколько пользователей оценило фильмы из списка list_of_best и сохраним результат в список - list_of_film_ratings ###
i=0
for x in list_of_best:
    list_of_film_ratings[i]=( list_of_film_ratings[i], len(ratings.query('userId == {}'.format(x)).filter(items = ['userId'])) )
    i=i+1
list_of_film_ratings = np.array(list_of_film_ratings)
### Теперь отсортируем список list_of_film_ratings по количеству оценок за тот или иной фильм и найдем id фильма с наибольшим количеством - best_of_the_best_ID ###
best_of_the_best_ID=int(list_of_film_ratings[list_of_film_ratings[:,1].argsort()][-1][0])
best_of_the_best_num=int(list_of_film_ratings[list_of_film_ratings[:,1].argsort()][-1][1])

In [4]:
movies = pd.read_csv('movies.csv')
### И наконец найдем best_of_the_best_ID в массиве movies и выведем на экран название фильма с наибольшим количеством наивысших оценок пользователей ###
print('Лучшим фильмом по мнению ' + str(best_of_the_best_num) + ' людей (' + str(round(10000*best_of_the_best_num/len(ratings))/100) + '% от общего числа) является:')
print(movies.query('movieId == {}'.format(best_of_the_best_ID)).filter(items = ['title']))

Лучшим фильмом по мнению 2391 людей (2.39% от общего числа) является:
                         title
490  Surviving the Game (1994)


### Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [5]:
power = pd.read_csv('power.csv')
buf=power.query('country == "Lithuania" or country == "Latvia" or country == "Estonia"').query('year >= 2005 and year <= 2010').query('category == 4 or category == 12 or category == 21').filter(items = ['quantity'])
sum_of_quantity=0
for x in buf.values.tolist():
   sum_of_quantity=sum_of_quantity+x[0]
print('Сумма по указанным ограничениям равна: ' + str(int(sum_of_quantity)))

Сумма по указанным ограничениям равна: 240481


### Задание 5
Решите систему уравнений:
\begin{equation*}
4x + 2y + z = 4 \\
x + 3y = 12 \\
5y + 4z = -3
\end{equation*}

In [6]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
print('Решение уравнения это вектор [x,y,z] равный: ' + str(linalg.solve(a, b)))

Решение уравнения это вектор [x,y,z] равный: [ 0.46666667  3.84444444 -5.55555556]
