### Задание 1.
Существует массив
#### Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],
как из него создать массив
#### R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]?

In [36]:
import numpy as np
Z=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
i=0
R=np.arange(44).reshape(11,4)
while i<=Z[-1]-4:
    R[:][i]=Z[i:4+i]
    i=i+1
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

### Задание 2.
Дана произвольная матрица A. Рассчитать ранг матрицы A.

In [57]:
A = np.random.uniform(0,1,(5,6))
print(A)
rank = np.linalg.matrix_rank(A)
print('Её ранг равен ' + str(rank))

[[0.40468632 0.8546994  0.47873509 0.23578658 0.21646982 0.20054237]
 [0.5650401  0.84945433 0.82396885 0.68646123 0.61545792 0.80718098]
 [0.24933024 0.66177034 0.23569582 0.0283255  0.25499003 0.09648511]
 [0.67241067 0.91741552 0.52270123 0.02792676 0.87313929 0.09102323]
 [0.48318181 0.72094658 0.76719755 0.26348787 0.16715968 0.78073515]]
Её ранг равен 5


### Задание 3.
Найти лучший алгоритм для решения следующей задачи:
#### min (x1x4(x1+x2+x3)+x3).
Условия:
#### x1x2x3x4≥30
#### x1^2+x2^2+x3^2+x4^2=60
#### 2≤x1,x2,x3,x4≤6
Начальное приближение:
#### x=(1,5,5,1)

In [22]:
from scipy import optimize
from scipy.optimize import Bounds
def f(x):
    return x[0]*x[3]*(x[0]+x[1]+x[2])+x[2]
print('в "scipy.optimize" всего два метода поддерживают сложные ограничения,\nзначит и выбирать приходится только между двумя "COBYLA" и "SLSQP".')
cons = ({'type': 'ineq', 'fun': lambda x: x[0]*x[1]*x[2]*x[3]-30},\
        {'type': 'ineq', 'fun': lambda x: x[0]**2+x[1]**2+x[2]**2+x[3]**2-60},\
        {'type': 'ineq', 'fun': lambda x: 60-x[0]**2-x[1]**2-x[2]**2-x[3]**2},\
        {'type': 'ineq', 'fun': lambda x: x[0]-2},\
        {'type': 'ineq', 'fun': lambda x: 6-x[0]},\
        {'type': 'ineq', 'fun': lambda x: x[1]-2},\
        {'type': 'ineq', 'fun': lambda x: 6-x[1]},\
        {'type': 'ineq', 'fun': lambda x: x[1]-2},\
        {'type': 'ineq', 'fun': lambda x: 6-x[1]},\
        {'type': 'ineq', 'fun': lambda x: x[1]-2},\
        {'type': 'ineq', 'fun': lambda x: 6-x[1]})

rez_COBYLA=optimize.minimize(f, [4,4,4,4], constraints=cons, method='COBYLA')
print('*****\n Результаты COBYLA:')
print(rez_COBYLA)
print('*****\n Результаты SLSQP:')
rez_SLSQP=optimize.minimize(f, [4,4,4,4], constraints=cons, method='SLSQP')
print(rez_SLSQP)
print('*****\n Итог:')
if rez_COBYLA.fun-rez_SLSQP.fun>0:
    print('SLSQP - лучше, так как его ошибка меньше')
else:
    print('COBYLA - лучше, так как его ошибка меньше')

в "scipy.optimize" всего два метода поддерживают сложные ограничения,
значит и выбирать приходится только между двумя "COBYLA" и "SLSQP".
*****
 Результаты COBYLA:
     fun: 18.444874233295803
   maxcv: 2.273900512328453e-09
 message: 'Optimization terminated successfully.'
    nfev: 58
  status: 1
 success: True
       x: array([2.00000218, 5.93087806, 4.52911104, 0.55841724])
*****
 Результаты SLSQP:
     fun: 18.445642139422315
     jac: array([ 8.08784962,  1.11905026,  2.11905026, 24.90969443])
 message: 'Optimization terminated successfully.'
    nfev: 111
     nit: 19
    njev: 18
  status: 0
 success: True
       x: array([2.        , 5.94680404, 4.50804319, 0.55952509])
*****
 Итог:
COBYLA - лучше, так как его ошибка меньше
