# Лабораторная работа по модулю “Python для анализа данных”

## 1
##### Дан произвольный список, содержащий только числа.
##### Выведите результат сложения всех чисел больше 10.

In [1]:
lst=[5,7,12,1,-77,110,0]
print('Дан список: ' + str(lst))
lst=sorted(lst)
i=0
for x in lst:
    if x>10:
        break
    i=i+1
print('Cумма элементов списка, который вольше 10 равна ' + str(sum(lst[i:])))

Дан список: [5, 7, 12, 1, -77, 110, 0]
Cумма элементов списка, который вольше 10 равна 122


## 2
##### Пусть задан список, содержащий строки.
##### Выведите все строки, заканчивающиеся буковой "r".

In [2]:
lst=['mayor','man', 'red', 'sir', 'old', 'peer', 'strong']
print('Дан список: ' + str(lst))
rez=[]
for x in lst:
    if x[-1]=='r':
        rez.append(x)
print('А вот строки из него, которые оканчиваются на "r": ' + str(rez))

Дан список: ['mayor', 'man', 'red', 'sir', 'old', 'peer', 'strong']
А вот строки из него, которые оканчиваются на "r": ['mayor', 'sir', 'peer']


## 3
##### Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащуютолько цифры.
##### Строка должна содержать хотя бы однуцифру 3. 

In [3]:
import random
num=random.randint(10000, 99999)
ix=random.randint(0,5)
rez=str(num)
if ix==0:    rez='3' + rez
elif ix==5:  rez=rez + '3'
else:        rez=rez[:ix] + '3' + rez[ix:]
print('Случайная строка из шести символов-цифр как минимум один из которых "3": ' + rez)

Случайная строка из шести символов-цифр как минимум один из которых "3": 713014


## 4
##### Пусть дана строка произвольной длины.
##### Выведите информацию о том,сколько в ней символов и сколько слов.

In [4]:
str0="To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles And by opposing end them."
print('Дана строка:\n' +str0 )
wrd=str0.split(' ')
print('Общее количество символов в ней ' + str(len(str0.replace(" ", ""))) + ', а слов ' + str(len(wrd)) + '.')

Дана строка:
To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles And by opposing end them.
Общее количество символов в ней 159, а слов 39.


## 5
##### Пусть дана матрица чисел размером NхN.
##### Представьте данную матрицу ввиде списка.
##### Выведите результат сложения всех элементов матрицы.

In [5]:
import numpy as np
mas1=np.array([ [1, 8, 3], [6, 5, 4], [7, 2, 9] ])
print('Дана матрица (numpy):\n' + str(mas1))

print('А вот она же, но уже в виде типа list:\n' + str(mas1.tolist()))

sz=mas1.shape
mas2=mas1.reshape((1, sz[0]*sz[1]))
print('Вот результат суммы всех её элементов: ' + str(sum(mas2.tolist()[0])))

Дана матрица (numpy):
[[1 8 3]
 [6 5 4]
 [7 2 9]]
А вот она же, но уже в виде типа list:
[[1, 8, 3], [6, 5, 4], [7, 2, 9]]
Вот результат суммы всех её элементов: 45


## 6
##### Пусть список студентов представлен в виде структуры:
###### [ [No, ФИО, Возраст,Группа],
######   [No, ФИО, Возраст, Группа],
######   [No, ФИО, Возраст, Группа] ]
##### Преобразуйте список в словарь вида:
###### { No: [ФИО, Возраст, Группа],
######   No: [....],
######   No: [....] }

In [6]:
lst=[[77, 'Бикбуллатов Бикбуллат Бикбуллатович', 19, 2], [47, 'Смирнов Игорь Викторович', 18, 7],[4, 'Wahlberg Elizabeth', 20, 3]]
print('Дан список студентов:\n' + str(lst))
dic={}
for x in lst:
    dic.setdefault(x[0], ['', 0, 0])
    dic[x[0]]=x[1:]
print('После преобазования в словарь он выглядит:\n' + str(dic))

Дан список студентов:
[[77, 'Бикбуллатов Бикбуллат Бикбуллатович', 19, 2], [47, 'Смирнов Игорь Викторович', 18, 7], [4, 'Wahlberg Elizabeth', 20, 3]]
После преобазования в словарь он выглядит:
{77: ['Бикбуллатов Бикбуллат Бикбуллатович', 19, 2], 47: ['Смирнов Игорь Викторович', 18, 7], 4: ['Wahlberg Elizabeth', 20, 3]}


## 7
##### Добавьте к задаче №6 для словаря возможность (без преобразования словаря обратно в список) изменить группу студента.
##### Поиск по «ФИО» («ФИО» студента и новый номер группы необходимо ввести с клавиатуры).

In [8]:
lst=[[77, 'Бикбуллатов Бикбуллат Бикбуллатович', 19, 2], [47, 'Смирнов Игорь Викторович', 18, 7],[4, 'Wahlberg Elizabeth', 20, 3]]
dic={}
for x in lst:
    dic.setdefault(x[0], ['', 0, 0])
    dic[x[0]]=x[1:]

def get_studID(dic, name):
    for key, value in dic.items():
        if value[0] == name:
            return key
        
print('Введите ФИО студента:\n')
stud_name=input()
print('Введите новый номер его группы:')
new_stud_group=int(input())

studID=get_studID(dic, stud_name)
dic[studID][-1]=new_stud_group
print('\nИзменения вступили в силу:\n' + str(dic))

Введите ФИО студента:

Введите новый номер его группы:

Изменения вступили в силу:
{77: ['Бикбуллатов Бикбуллат Бикбуллатович', 19, 1], 47: ['Смирнов Игорь Викторович', 18, 7], 4: ['Wahlberg Elizabeth', 20, 3]}


## 8
##### Дана некоторая директория (папка).
##### Посчитайте количество файлов в данной директории (папке) и выведите на  экра

In [9]:
from os import listdir
from os.path import isfile
from os.path import join as joinpath
### Путь к папке (можно задать любой) - mypath ###
mypath = "/"
i=0
rez='('
for x in listdir(mypath):
    if isfile(joinpath(mypath,x)):
        rez=rez + ' ' + x + ' ,'
        i=i+1
rez=rez[:-1] + ')'
print('В указанной папке находится '+ str(i) +' файлов со следующими именами:\n' + rez)

В указанной папке находится 5 файлов со следующими именами:
( initrd.img.old , initrd.img , swapfile , vmlinuz , vmlinuz.old )
